modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/EltyDev/Miners-dream/issues"
license = "GNU General Public License v3.0"

[[mods]]
modId = "miners_dream"
version = "${version}"
displayName = "Miner's dream"
authors = "Elty"
description = '''
Port of miner's dream from Orespawn
'''
#logoFile = ""

[[dependencies.miners_dream]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.miners_dream]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.miners_dream]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "miners_dream.mixins.json"
